"""initial schema

Revision ID: 0001
Revises:
Create Date: 2026-09-18 10:30:39.866355
"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "kv",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.PrimaryKeyConstraint("key", name=op.f("pk_kv")),
    )
    op.create_table(
        "users",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("max_user_id", sa.BigInteger(), nullable=False),
        sa.Column("first_name", sa.String(length=256), nullable=False),
        sa.Column("lang", sa.String(length=8), nullable=False),
        sa.Column("consent_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("lang in ('ru', 'en')", name=op.f("ck_users_lang")),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_users")),
        sa.UniqueConstraint("max_user_id", name=op.f("uq_users_max_user_id")),
    )
    op.create_table(
        "checkin_attempts",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column("success", sa.Boolean(), nullable=False),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_checkin_attempts_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_checkin_attempts")),
    )
    op.create_index(
        "ix_checkin_attempts_user_id_created_at",
        "checkin_attempts",
        ["user_id", "created_at"],
        unique=False,
    )
    op.create_table(
        "events",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("title", sa.String(length=200), nullable=False),
        sa.Column("description", sa.Text(), nullable=False),
        sa.Column("kind", sa.String(length=64), nullable=False),
        sa.Column("location", sa.String(length=200), nullable=False),
        sa.Column("starts_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("ends_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("onboarding_step", sa.Text(), nullable=True),
        sa.Column("organizer_id", sa.BigInteger(), nullable=False),
        sa.Column("qr_seed", sa.LargeBinary(), nullable=False),
        sa.Column("checkin_open", sa.Boolean(), server_default=sa.text("false"), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("ends_at > starts_at", name=op.f("ck_events_time_range")),
        sa.CheckConstraint("points >= 0", name=op.f("ck_events_points_non_negative")),
        sa.ForeignKeyConstraint(
            ["organizer_id"],
            ["users.id"],
            name=op.f("fk_events_organizer_id_users"),
            ondelete="RESTRICT",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_events")),
    )
    op.create_index(
        "ix_events_organizer_id_starts_at", "events", ["organizer_id", "starts_at"], unique=False
    )
    op.create_index("ix_events_starts_at", "events", ["starts_at"], unique=False)
    op.create_table(
        "manual_step_completions",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("step_key", sa.String(length=64), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
            name=op.f("fk_manual_step_completions_user_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("user_id", "step_key", name=op.f("pk_manual_step_completions")),
    )
    op.create_table(
        "organizer_invites",
        sa.Column("token", sa.Text(), nullable=False),
        sa.Column("created_by", sa.BigInteger(), nullable=True),
        sa.Column("expires_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("used_by", sa.BigInteger(), nullable=True),
        sa.Column("used_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["created_by"],
            ["users.id"],
            name=op.f("fk_organizer_invites_created_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["used_by"],
            ["users.id"],
            name=op.f("fk_organizer_invites_used_by_users"),
            ondelete="SET NULL",
        ),
        sa.PrimaryKeyConstraint("token", name=op.f("pk_organizer_invites")),
    )
    op.create_table(
        "organizers",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("invited_by", sa.BigInteger(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["invited_by"],
            ["users.id"],
            name=op.f("fk_organizers_invited_by_users"),
            ondelete="SET NULL",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_organizers_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", name=op.f("pk_organizers")),
    )
    op.create_table(
        "outbox",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("kind", sa.String(length=32), nullable=False),
        sa.Column("payload", postgresql.JSONB(astext_type=sa.Text()), nullable=False),
        sa.Column("run_at", sa.DateTime(timezone=True), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("attempts", sa.Integer(), server_default=sa.text("0"), nullable=False),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("dedup_key", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "kind in ('reminder', 'checkin_confirmed', 'step_completed', 'invite_accepted', 'qr_display_start')",
            name=op.f("ck_outbox_kind"),
        ),
        sa.CheckConstraint(
            "status in ('pending', 'sent', 'failed', 'cancelled')", name=op.f("ck_outbox_status")
        ),
        sa.CheckConstraint("attempts >= 0", name=op.f("ck_outbox_attempts_non_negative")),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_outbox_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_outbox")),
    )
    op.create_index("ix_outbox_status_run_at", "outbox", ["status", "run_at"], unique=False)
    op.create_index(
        "uq_outbox_dedup_key",
        "outbox",
        ["dedup_key"],
        unique=True,
        postgresql_where=sa.text("dedup_key is not null"),
    )
    op.create_table(
        "checkins",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("method", sa.String(length=8), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint("method in ('qr', 'code')", name=op.f("ck_checkins_method")),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_checkins_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_checkins_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "event_id", name=op.f("pk_checkins")),
    )
    op.create_table(
        "qr_displays",
        sa.Column("id", sa.BigInteger(), sa.Identity(always=False), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column("organizer_id", sa.BigInteger(), nullable=False),
        sa.Column("max_chat_id", sa.BigInteger(), nullable=True),
        sa.Column("max_user_id", sa.BigInteger(), nullable=True),
        sa.Column("message_id", sa.Text(), nullable=True),
        sa.Column("active_until", sa.DateTime(timezone=True), nullable=False),
        sa.Column("last_rendered_window", sa.BigInteger(), nullable=True),
        sa.Column("stopped_at", sa.DateTime(timezone=True), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.CheckConstraint(
            "max_chat_id is not null or max_user_id is not null",
            name=op.f("ck_qr_displays_destination_present"),
        ),
        sa.ForeignKeyConstraint(
            ["event_id"],
            ["events.id"],
            name=op.f("fk_qr_displays_event_id_events"),
            ondelete="CASCADE",
        ),
        sa.ForeignKeyConstraint(
            ["organizer_id"],
            ["users.id"],
            name=op.f("fk_qr_displays_organizer_id_users"),
            ondelete="CASCADE",
        ),
        sa.PrimaryKeyConstraint("id", name=op.f("pk_qr_displays")),
    )
    op.create_index("ix_qr_displays_active_until", "qr_displays", ["active_until"], unique=False)
    op.create_index(
        "uq_qr_displays_organizer_id_event_id_active",
        "qr_displays",
        ["organizer_id", "event_id"],
        unique=True,
        postgresql_where=sa.text("stopped_at is null"),
    )
    op.create_table(
        "rsvps",
        sa.Column("user_id", sa.BigInteger(), nullable=False),
        sa.Column("event_id", sa.BigInteger(), nullable=False),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(
            ["event_id"], ["events.id"], name=op.f("fk_rsvps_event_id_events"), ondelete="CASCADE"
        ),
        sa.ForeignKeyConstraint(
            ["user_id"], ["users.id"], name=op.f("fk_rsvps_user_id_users"), ondelete="CASCADE"
        ),
        sa.PrimaryKeyConstraint("user_id", "event_id", name=op.f("pk_rsvps")),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("rsvps")
    op.drop_index(
        "uq_qr_displays_organizer_id_event_id_active",
        table_name="qr_displays",
        postgresql_where=sa.text("stopped_at is null"),
    )
    op.drop_index("ix_qr_displays_active_until", table_name="qr_displays")
    op.drop_table("qr_displays")
    op.drop_table("checkins")
    op.drop_index(
        "uq_outbox_dedup_key",
        table_name="outbox",
        postgresql_where=sa.text("dedup_key is not null"),
    )
    op.drop_index("ix_outbox_status_run_at", table_name="outbox")
    op.drop_table("outbox")
    op.drop_table("organizers")
    op.drop_table("organizer_invites")
    op.drop_table("manual_step_completions")
    op.drop_index("ix_events_starts_at", table_name="events")
    op.drop_index("ix_events_organizer_id_starts_at", table_name="events")
    op.drop_table("events")
    op.drop_index("ix_checkin_attempts_user_id_created_at", table_name="checkin_attempts")
    op.drop_table("checkin_attempts")
    op.drop_table("users")
    op.drop_table("kv")
    # ### end Alembic commands ###
